baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'ODAP'

homepage:
  show_call_box: false
logo:
  mobile: "img/logo/logo.svg"
  desktop: "img/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'Outbreak Data Analysis Platform'

seo:
  meta_og_title: "Outbreak Data Analysis Platform"
  meta_og_type: "website"
  meta_og_url: "https://odap.ac.uk"
  meta_og_image: "https://odap.ac.uk/img/logo/logo.svg"
  meta_og_description: "Outbreak Data Analysis Platform."
  meta_twitter_card: "summary"
  meta_twitter_site: ""
  meta_twitter_creator: ""

collections:
  outputs:
    output: true
    permalink: /outputs/:path/
  team:
    output: true
    permalink: /team/:path/

defaults:
  - scope:
      type: outputs
    values:
      layout: output
      bodyClass: page-outputs-single
  - scope:
      path: 'img'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

destination: _site






