####################################################
#
# Welcome to Redron Jekyll Template
#
# Product Link : https://themeix.com/product/redron-jekyll-template/
# Version : v1.0.0
#
####################################################

# Site settings

title: ODAP - Outbreak Data Analysis Platform
masthead_title: "ODAP"
email: odap@ed.ac.uk
baseurl: "" # the subpath of your site, e.g. /blog
description: >- # this means to ignore newlines until "baseurl:"
  ODAP facilitates biomedical research to advance understanding of disease caused by emerging or re-emerging pathogens.
url: "odap.ac.uk" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  odap-ac-uk
repository: "odap-ac-uk/odap.ac.uk"
logo: "/assets/img/logo/logo.svg"
keywords: "pandemic, covid, genetics, genomics, data, analysis, TRE"

# Build settings
markdown: kramdown
theme: minima

collections:
  services:
    output: true
    permalink: /service/:path/
  projects:
    output: true
    permalink: /project/:path/
  people:
    output: true
    permalink: /team/:path/
  outputs:
    output: true
    permalink: /output/:path/

defaults:
  - scope:
      type: outputs
    values:
      layout: output